### ISSUE TITLE
Newly created skill doesnt show up in alexa.amazon.com nor in companion app

### ISSUE THREAD

**Issue by akshayvernekar** [alexa/skill-sample-python-smarthome-iot#5]
Hi team, I followed the instructions in both the automated way as well as manual yet I am facing the same issue wherein I can see that the skill is created in developer.amazon.com but fails to show up in the alexa companion app as well as alexa.amazon.com under the dev skills section ,
![screenshot from 2019-01-10 16 29 33](https://user-images.githubusercontent.com/7204438/50955780-f23a6600-14f4-11e9-9de6-f4f17de7c7a0.png)
 . 
![screenshot from 2019-01-10 16 27 58](https://user-images.githubusercontent.com/7204438/50955702-c919d580-14f4-11e9-84e6-95f712bdef83.png)

**Comment by akshayvernekar** [comment]
I created a new amazon developer account and tried  again it is showing now, still not sure why it was not showing with the previous developer account.

**Comment by mikemaas-amazon** [comment]
Thank you, I am glad this is resolved.
